name = "EquationsOfStateOfSolidsBase"
uuid = "6f256da5-bf51-47e5-be7a-d1b13c30faeb"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
