name = "EquationsOfStateOfSolidsBase"
uuid = "6f256da5-bf51-47e5-be7a-d1b13c30faeb"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
EquationsOfState = "0438fec6-b81c-52d9-9651-d286848f50a8"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
